# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.31.0
    hooks:
      - id: terraform_tflint
        args:
          - 'args=--deep'
      - id: terraform_docs
      # - id: terraform_tfsec

  - repo:  https://github.com/gruntwork-io/pre-commit
    rev: v0.1.3
    hooks:
      - id: terraform-fmt
