# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.69.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - 'args=--deep'
      # - id: terraform_tfsec
      #   exclude: other-code-example # uncomment to check the sub folder as well
      # - id: terraform_docs

  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.2.0
  #   hooks:
  #     - id: detect-secrets
  #       args: ['--baseline', '.pre-commit-config/.secrets.baseline']
  #       exclude: .*/tests/.*

  # - repo: https://github.com/frnmst/md-toc
  #   rev: 8.1.3
  #   hooks:
  #     - id: md-toc
  #       language_version: python3
